version: '3.9'

services:
    mysql:
        image: mysql:8.1
        container_name: laravel-mysql
        restart: no
        env_file:
            - .env
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

volumes:
    mysql_data:
